// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module axi_encrypt_u64_to_u8_array (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        b_0_address0,
        b_0_ce0,
        b_0_we0,
        b_0_d0,
        b_1_address0,
        b_1_ce0,
        b_1_we0,
        b_1_d0,
        b_2_address0,
        b_2_ce0,
        b_2_we0,
        b_2_d0,
        b_3_address0,
        b_3_ce0,
        b_3_we0,
        b_3_d0,
        idx,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] a;
output  [2:0] b_0_address0;
output   b_0_ce0;
output   b_0_we0;
output  [7:0] b_0_d0;
output  [2:0] b_1_address0;
output   b_1_ce0;
output   b_1_we0;
output  [7:0] b_1_d0;
output  [2:0] b_2_address0;
output   b_2_ce0;
output   b_2_we0;
output  [7:0] b_2_d0;
output  [2:0] b_3_address0;
output   b_3_ce0;
output   b_3_we0;
output  [7:0] b_3_d0;
input  [4:0] idx;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[2:0] b_0_address0;
reg b_0_ce0;
reg b_0_we0;
reg[7:0] b_0_d0;
reg[2:0] b_1_address0;
reg b_1_ce0;
reg b_1_we0;
reg[7:0] b_1_d0;
reg[2:0] b_2_address0;
reg b_2_ce0;
reg b_2_we0;
reg[7:0] b_2_d0;
reg[2:0] b_3_address0;
reg b_3_ce0;
reg b_3_we0;
reg[7:0] b_3_d0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] empty_fu_354_p1;
reg   [1:0] empty_reg_634;
reg   [2:0] b_0_addr_reg_638;
reg   [2:0] b_1_addr_reg_643;
reg   [2:0] b_2_addr_reg_648;
reg   [2:0] b_3_addr_reg_653;
reg   [7:0] trunc_ln13_1_reg_658;
reg   [2:0] b_0_addr_5_reg_666;
reg   [2:0] b_1_addr_5_reg_671;
reg   [2:0] b_2_addr_5_reg_676;
reg   [2:0] b_3_addr_5_reg_681;
reg   [7:0] trunc_ln13_2_reg_686;
reg   [2:0] b_0_addr_6_reg_694;
reg   [2:0] b_1_addr_6_reg_699;
reg   [2:0] b_2_addr_6_reg_704;
reg   [2:0] b_3_addr_6_reg_709;
reg   [7:0] trunc_ln13_3_reg_714;
reg   [2:0] b_0_addr_7_reg_722;
reg   [2:0] b_1_addr_7_reg_727;
reg   [2:0] b_2_addr_7_reg_732;
reg   [2:0] b_3_addr_7_reg_737;
reg   [7:0] trunc_ln13_4_reg_742;
wire   [63:0] zext_ln7_fu_410_p1;
wire   [63:0] zext_ln13_fu_436_p1;
wire   [63:0] zext_ln13_1_fu_468_p1;
wire   [63:0] zext_ln13_2_fu_500_p1;
wire   [63:0] zext_ln13_3_fu_532_p1;
wire   [63:0] zext_ln13_4_fu_560_p1;
wire   [63:0] zext_ln13_5_fu_588_p1;
wire   [63:0] zext_ln13_6_fu_616_p1;
wire   [7:0] trunc_ln13_fu_418_p1;
wire    ap_CS_fsm_state2;
wire   [2:0] lshr_ln7_fu_400_p4;
wire   [4:0] add_ln7_6_fu_394_p2;
wire   [2:0] lshr_ln_fu_426_p4;
wire   [4:0] add_ln7_5_fu_388_p2;
wire   [2:0] lshr_ln13_8_fu_458_p4;
wire   [4:0] add_ln7_4_fu_382_p2;
wire   [2:0] lshr_ln13_s_fu_490_p4;
wire   [4:0] add_ln7_3_fu_376_p2;
wire   [2:0] lshr_ln13_1_fu_522_p4;
wire   [4:0] add_ln7_2_fu_370_p2;
wire   [2:0] lshr_ln13_2_fu_550_p4;
wire   [4:0] add_ln7_1_fu_364_p2;
wire   [2:0] lshr_ln13_3_fu_578_p4;
wire   [4:0] add_ln7_fu_358_p2;
wire   [2:0] lshr_ln13_4_fu_606_p4;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        b_0_addr_5_reg_666 <= zext_ln13_4_fu_560_p1;
        b_0_addr_6_reg_694 <= zext_ln13_5_fu_588_p1;
        b_0_addr_7_reg_722 <= zext_ln13_6_fu_616_p1;
        b_0_addr_reg_638 <= zext_ln7_fu_410_p1;
        b_1_addr_5_reg_671 <= zext_ln13_4_fu_560_p1;
        b_1_addr_6_reg_699 <= zext_ln13_5_fu_588_p1;
        b_1_addr_7_reg_727 <= zext_ln13_6_fu_616_p1;
        b_1_addr_reg_643 <= zext_ln7_fu_410_p1;
        b_2_addr_5_reg_676 <= zext_ln13_4_fu_560_p1;
        b_2_addr_6_reg_704 <= zext_ln13_5_fu_588_p1;
        b_2_addr_7_reg_732 <= zext_ln13_6_fu_616_p1;
        b_2_addr_reg_648 <= zext_ln7_fu_410_p1;
        b_3_addr_5_reg_681 <= zext_ln13_4_fu_560_p1;
        b_3_addr_6_reg_709 <= zext_ln13_5_fu_588_p1;
        b_3_addr_7_reg_737 <= zext_ln13_6_fu_616_p1;
        b_3_addr_reg_653 <= zext_ln7_fu_410_p1;
        empty_reg_634 <= empty_fu_354_p1;
        trunc_ln13_1_reg_658 <= {{a[39:32]}};
        trunc_ln13_2_reg_686 <= {{a[47:40]}};
        trunc_ln13_3_reg_714 <= {{a[55:48]}};
        trunc_ln13_4_reg_742 <= {{a[63:56]}};
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (1'b0 == ap_ce))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((empty_reg_634 == 2'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        b_0_address0 = b_0_addr_7_reg_722;
    end else if (((empty_reg_634 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        b_0_address0 = b_0_addr_5_reg_666;
    end else if (((empty_reg_634 == 2'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        b_0_address0 = b_0_addr_6_reg_694;
    end else if (((empty_reg_634 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        b_0_address0 = b_0_addr_reg_638;
    end else if (((empty_fu_354_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        b_0_address0 = zext_ln13_2_fu_500_p1;
    end else if (((empty_fu_354_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        b_0_address0 = zext_ln13_fu_436_p1;
    end else if (((empty_fu_354_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        b_0_address0 = zext_ln13_1_fu_468_p1;
    end else if (((empty_fu_354_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        b_0_address0 = zext_ln13_3_fu_532_p1;
    end else begin
        b_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((empty_reg_634 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        b_0_ce0 = 1'b1;
    end else begin
        b_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((empty_reg_634 == 2'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        b_0_d0 = trunc_ln13_3_reg_714;
    end else if (((empty_reg_634 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        b_0_d0 = trunc_ln13_1_reg_658;
    end else if (((empty_reg_634 == 2'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        b_0_d0 = trunc_ln13_2_reg_686;
    end else if (((empty_reg_634 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        b_0_d0 = trunc_ln13_4_reg_742;
    end else if (((empty_fu_354_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        b_0_d0 = {{a[23:16]}};
    end else if (((empty_fu_354_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        b_0_d0 = trunc_ln13_fu_418_p1;
    end else if (((empty_fu_354_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        b_0_d0 = {{a[15:8]}};
    end else if (((empty_fu_354_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        b_0_d0 = {{a[31:24]}};
    end else begin
        b_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((empty_reg_634 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        b_0_we0 = 1'b1;
    end else begin
        b_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((empty_reg_634 == 2'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        b_1_address0 = b_1_addr_6_reg_699;
    end else if (((empty_reg_634 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        b_1_address0 = b_1_addr_reg_643;
    end else if (((empty_reg_634 == 2'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        b_1_address0 = b_1_addr_5_reg_671;
    end else if (((empty_reg_634 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        b_1_address0 = b_1_addr_7_reg_727;
    end else if (((empty_fu_354_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        b_1_address0 = zext_ln13_1_fu_468_p1;
    end else if (((empty_fu_354_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        b_1_address0 = zext_ln13_3_fu_532_p1;
    end else if (((empty_fu_354_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        b_1_address0 = zext_ln13_fu_436_p1;
    end else if (((empty_fu_354_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        b_1_address0 = zext_ln13_2_fu_500_p1;
    end else begin
        b_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((empty_reg_634 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        b_1_ce0 = 1'b1;
    end else begin
        b_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((empty_reg_634 == 2'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        b_1_d0 = trunc_ln13_2_reg_686;
    end else if (((empty_reg_634 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        b_1_d0 = trunc_ln13_4_reg_742;
    end else if (((empty_reg_634 == 2'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        b_1_d0 = trunc_ln13_1_reg_658;
    end else if (((empty_reg_634 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        b_1_d0 = trunc_ln13_3_reg_714;
    end else if (((empty_fu_354_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        b_1_d0 = {{a[15:8]}};
    end else if (((empty_fu_354_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        b_1_d0 = {{a[31:24]}};
    end else if (((empty_fu_354_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        b_1_d0 = trunc_ln13_fu_418_p1;
    end else if (((empty_fu_354_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        b_1_d0 = {{a[23:16]}};
    end else begin
        b_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((empty_reg_634 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        b_1_we0 = 1'b1;
    end else begin
        b_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((empty_reg_634 == 2'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        b_2_address0 = b_2_addr_5_reg_676;
    end else if (((empty_reg_634 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        b_2_address0 = b_2_addr_7_reg_732;
    end else if (((empty_reg_634 == 2'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        b_2_address0 = b_2_addr_reg_648;
    end else if (((empty_reg_634 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        b_2_address0 = b_2_addr_6_reg_704;
    end else if (((empty_fu_354_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        b_2_address0 = zext_ln13_fu_436_p1;
    end else if (((empty_fu_354_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        b_2_address0 = zext_ln13_2_fu_500_p1;
    end else if (((empty_fu_354_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        b_2_address0 = zext_ln13_3_fu_532_p1;
    end else if (((empty_fu_354_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        b_2_address0 = zext_ln13_1_fu_468_p1;
    end else begin
        b_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((empty_reg_634 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        b_2_ce0 = 1'b1;
    end else begin
        b_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((empty_reg_634 == 2'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        b_2_d0 = trunc_ln13_1_reg_658;
    end else if (((empty_reg_634 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        b_2_d0 = trunc_ln13_3_reg_714;
    end else if (((empty_reg_634 == 2'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        b_2_d0 = trunc_ln13_4_reg_742;
    end else if (((empty_reg_634 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        b_2_d0 = trunc_ln13_2_reg_686;
    end else if (((empty_fu_354_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        b_2_d0 = trunc_ln13_fu_418_p1;
    end else if (((empty_fu_354_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        b_2_d0 = {{a[23:16]}};
    end else if (((empty_fu_354_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        b_2_d0 = {{a[31:24]}};
    end else if (((empty_fu_354_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        b_2_d0 = {{a[15:8]}};
    end else begin
        b_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((empty_reg_634 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        b_2_we0 = 1'b1;
    end else begin
        b_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((empty_reg_634 == 2'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        b_3_address0 = b_3_addr_reg_653;
    end else if (((empty_reg_634 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        b_3_address0 = b_3_addr_6_reg_709;
    end else if (((empty_reg_634 == 2'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        b_3_address0 = b_3_addr_7_reg_737;
    end else if (((empty_reg_634 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        b_3_address0 = b_3_addr_5_reg_681;
    end else if (((empty_fu_354_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        b_3_address0 = zext_ln13_3_fu_532_p1;
    end else if (((empty_fu_354_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        b_3_address0 = zext_ln13_1_fu_468_p1;
    end else if (((empty_fu_354_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        b_3_address0 = zext_ln13_2_fu_500_p1;
    end else if (((empty_fu_354_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        b_3_address0 = zext_ln13_fu_436_p1;
    end else begin
        b_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((empty_reg_634 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        b_3_ce0 = 1'b1;
    end else begin
        b_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((empty_reg_634 == 2'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        b_3_d0 = trunc_ln13_4_reg_742;
    end else if (((empty_reg_634 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        b_3_d0 = trunc_ln13_2_reg_686;
    end else if (((empty_reg_634 == 2'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        b_3_d0 = trunc_ln13_3_reg_714;
    end else if (((empty_reg_634 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        b_3_d0 = trunc_ln13_1_reg_658;
    end else if (((empty_fu_354_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        b_3_d0 = {{a[31:24]}};
    end else if (((empty_fu_354_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        b_3_d0 = {{a[15:8]}};
    end else if (((empty_fu_354_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        b_3_d0 = {{a[23:16]}};
    end else if (((empty_fu_354_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        b_3_d0 = trunc_ln13_fu_418_p1;
    end else begin
        b_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((empty_reg_634 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((empty_reg_634 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd3) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd2) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (empty_fu_354_p1 == 2'd0) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        b_3_we0 = 1'b1;
    end else begin
        b_3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln7_1_fu_364_p2 = (idx + 5'd2);

assign add_ln7_2_fu_370_p2 = (idx + 5'd3);

assign add_ln7_3_fu_376_p2 = (idx + 5'd4);

assign add_ln7_4_fu_382_p2 = (idx + 5'd5);

assign add_ln7_5_fu_388_p2 = (idx + 5'd6);

assign add_ln7_6_fu_394_p2 = (idx + 5'd7);

assign add_ln7_fu_358_p2 = (idx + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign empty_fu_354_p1 = idx[1:0];

assign lshr_ln13_1_fu_522_p4 = {{add_ln7_3_fu_376_p2[4:2]}};

assign lshr_ln13_2_fu_550_p4 = {{add_ln7_2_fu_370_p2[4:2]}};

assign lshr_ln13_3_fu_578_p4 = {{add_ln7_1_fu_364_p2[4:2]}};

assign lshr_ln13_4_fu_606_p4 = {{add_ln7_fu_358_p2[4:2]}};

assign lshr_ln13_8_fu_458_p4 = {{add_ln7_5_fu_388_p2[4:2]}};

assign lshr_ln13_s_fu_490_p4 = {{add_ln7_4_fu_382_p2[4:2]}};

assign lshr_ln7_fu_400_p4 = {{idx[4:2]}};

assign lshr_ln_fu_426_p4 = {{add_ln7_6_fu_394_p2[4:2]}};

assign trunc_ln13_fu_418_p1 = a[7:0];

assign zext_ln13_1_fu_468_p1 = lshr_ln13_8_fu_458_p4;

assign zext_ln13_2_fu_500_p1 = lshr_ln13_s_fu_490_p4;

assign zext_ln13_3_fu_532_p1 = lshr_ln13_1_fu_522_p4;

assign zext_ln13_4_fu_560_p1 = lshr_ln13_2_fu_550_p4;

assign zext_ln13_5_fu_588_p1 = lshr_ln13_3_fu_578_p4;

assign zext_ln13_6_fu_616_p1 = lshr_ln13_4_fu_606_p4;

assign zext_ln13_fu_436_p1 = lshr_ln_fu_426_p4;

assign zext_ln7_fu_410_p1 = lshr_ln7_fu_400_p4;

endmodule //axi_encrypt_u64_to_u8_array
